<?php

namespace Siarme\GeneralBundle\Repository;

/**
 * ItemSolicitadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemSolicitadoRepository extends \Doctrine\ORM\EntityRepository
{
}
