<?php

namespace Siarme\GeneralBundle\Repository;

/**
 * ItemAcuerdoMarcoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemAcuerdoMarcoRepository extends \Doctrine\ORM\EntityRepository
{
}
