<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * ItemProcesoAdjudicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemProcesoAdjudicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
